# Copyright (C) 2020 Huawei Technologies Co., Ltd. All rights reserved.

[base]
name = "pose_infer"
device = "rknpu"
version = "1.0.0"
description = "lightweight_openpose_288x512_rknpu2"
entry = "./lightweight_openpose_288x512_rknpu2.rknn"  # model file path, use relative path
type = "inference" 
virtual_type = "rknpu2" # inference engine type: rockchip now support rknpu, rknpu2(if exist)
group_type = "Inference"  # flowunit group attribution, do not change
is_input_contiguous = "false" # rk do not support memory combine, fix, do not change

[input]
[input.input1]
name = "input"
type = "uint8"
device = "rknpu"

[output]
[output.output1]
name = "out_heatmaps"
type = "float"

[output.output2]
name = "out_pafs"
type = "float"
