# Copyright (C) 2020 Huawei Technologies Co., Ltd. All rights reserved.

[base]
name = "mask_infer"
device = "rknpu"
version = "1.0.0"
description = "your description"
entry = "./yolo3_resnet18_mask_det_288x512_rknpu2.rknn"  # model file path, use relative path
type = "inference" 
virtual_type = "rknpu2" # inference engine type: rockchip now support rknpu, rknpu2(if exist)
group_type = "Inference"  # flowunit group attribution, do not change
is_input_contiguous = "false" # rk do not support memory combine, fix, do not change

[input]
[input.input1]
name = "data"
type = "uint8"
device = "rknpu"

[output]
[output.output1]
name = "yolo/output1"
type = "float"

[output.output2]
name = "yolo/output2"
type = "float"

[output.output3]
name = "yolo/output3"
type = "float"
