# Copyright (c) Huawei Technologies Co., Ltd. 2022. All rights reserved.

# Basic config
[base]
name = "pose_post_light" # The FlowUnit name
device = "cpu" # The device the flowunit runs on，cpu
version = "1.0.0" # The version of the flowunit
type = "python" # Fixed value, do not change
description = "description" # The description of the flowunit
entry = "pose_post_light@pose_post_lightFlowUnit" # Python flowunit entry function
group_type = "python"  # flowunit group attribution, change as input/output/image ...

# Flowunit Type
stream = false # Whether the flowunit is a stream flowunit
condition  = false # Whether the flowunit is a condition flowunit
collapse = false # Whether the flowunit is a collapse flowunit
collapse_all = false # Whether the flowunit will collapse all the data
expand = false #  Whether the flowunit is a expand flowunit

[config]
net_h = 288
net_w = 512
num_kpts = 18
stride = 8
upsample_ratio = 4

[input]
[input.input1]
name = "in_heatmaps"
type = "float"

[input.input2]
name = "in_pafs"
type = "float"

[output]
[output.output1]
name = "out_pose"
type = "string"
