# Copyright (c) Huawei Technologies Co., Ltd. 2022. All rights reserved.

[driver]
dir = ["${HILENS_APP_ROOT}/etc/flowunit",
"${HILENS_APP_ROOT}/etc/flowunit/cpp",
"${HILENS_APP_ROOT}/model",
"${HILENS_MB_SDK_PATH}/flowunit"]
skip-default = true
[profile]
profile=false
trace=false
dir="${HILENS_DATA_DIR}/mb_profile"
[graph]
format = "graphviz"
graphconf = """digraph MODULENAME {
    node [shape=Mrecord]
    queue_size = 4
    batch_size = 1
    input1[type=input,flowunit=input,device=cpu,deviceid=0]

    data_source_parser[type=flowunit, flowunit=data_source_parser, device=cpu, deviceid=0]
    local_camera[type=flowunit, flowunit=local_camera, device=rknpu, deviceid=0, pix_fmt="bgr", cam_width=1280, cam_height=720]
    image_resize[type=flowunit, flowunit=resize, device=rknpu, deviceid=0, width=512, height=288]
    mask_detection[type=flowunit, flowunit=mask_infer, device=rknpu, deviceid=0]
    yolo3_post[type=flowunit, flowunit=yolo3_post, device=cpu, deviceid=0]
    draw_mask_bbox[type=flowunit, flowunit=draw_mask_bbox, device=cpu, deviceid=0]
    video_out[type=flowunit, flowunit=video_out, device=rknpu, deviceid=0]
    
    input1:input -> data_source_parser:in_data
    data_source_parser:out_video_url -> local_camera:in_camera_packet
    local_camera:out_camera_frame -> image_resize:in_image
    image_resize:out_image -> mask_detection:data
    mask_detection:"yolo/output1" -> yolo3_post:in_feat1
    mask_detection:"yolo/output2" -> yolo3_post:in_feat2
    mask_detection:"yolo/output3" -> yolo3_post:in_feat3
    local_camera:out_camera_frame -> draw_mask_bbox:in_image
    yolo3_post:out_data -> draw_mask_bbox:in_bbox
    draw_mask_bbox:out_image -> video_out:in_video_frame
}"""
[flow]
desc = "MODULENAME run in SDKNAME"
